# Generated by Django 4.0.2 on 2022-02-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='group',
        ),
    ]
