# Generated by Django 4.0.2 on 2022-02-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_remove_discipline_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('folderPath', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('idComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.comments')),
                ('idDiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.discipline')),
                ('idGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.group')),
                ('idHomework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.homework')),
                ('idTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('idDiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.discipline')),
            ],
        ),
        migrations.DeleteModel(
            name='Torrent',
        ),
        migrations.AddField(
            model_name='user',
            name='idSubGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.subgroup'),
        ),
    ]
