# Generated by Django 4.0.2 on 2022-02-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_comments_homework_lesson_subgroup_delete_torrent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
